### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by FaloonAI** [g3th/Windscribe-Signup#3]
When launched, the browser opens and displays the error:

Traceback (most recent call last):
  File "C:\Users\???\Downloads\Windscribe-Signup-main\windscribe.py", line 114, in <module>
    username = u.generate_a_username()
  File "C:\Users\???\Downloads\Windscribe-Signup-main\generator.py", line 50, in generate_a_username
    return adjective.text.capitalize() + noun.text.capitalize()
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by FaloonAI** [comment]
Linux:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/pytesseract/pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract'

During handling of the above exception, another exception occurred:
                                                                             
Traceback (most recent call last):                                           
  File "/home/kali/Documents/Windscribe-Signup-main/windscribe.py", line 121, in <module>                                                                 
    captcha_result = registration.read_captcha_by_ocr(captcha_screenshot_file_path).strip()                                                               
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                       
  File "/home/kali/Documents/Windscribe-Signup-main/registration.py", line 66, in read_captcha_by_ocr                                                     
    captcha = pytesseract.image_to_string(openImage)                         
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                         
  File "/home/kali/.local/lib/python3.11/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string                                          
    return {                                                                 
           ^                                                                 
  File "/home/kali/.local/lib/python3.11/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>                                                 
    Output.STRING: lambda: run_and_get_output(*args),                        
                           ^^^^^^^^^^^^^^^^^^^^^^^^^                         
  File "/home/kali/.local/lib/python3.11/site-packages/pytesseract/pytesseract.py", line 288, in run_and_get_output                                       
    run_tesseract(**kwargs)                                                  
  File "/home/kali/.local/lib/python3.11/site-packages/pytesseract/pytesseract.py", line 260, in run_tesseract                                            
    raise TesseractNotFoundError()                                           
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

**Comment by FaloonAI** [comment]
After updating the tesseract, everything started working on Linux. But the tesseract cannot recognize the captcha.
